name = "ATPLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ATPLean"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "Cli"
scope = "leanprover"

[[lean_lib]]
name = "ATPLean"
srcDir = "./src/"

# [package]
# name = "myproject"
# lean_version = "leanprover/lean4:nightly"
# require = ["mathlib"]

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4", rev = "master" }
lean4-cli = { git = "https://github.com/leanprover/lean4-cli", rev = "main" }


[[lean_lib]]
name = "Preprocessing"
srcDir = "./src/"
[[lean_exe]]
name = "preprocessor"
root = "Preprocessing.Main"
exeName = "pp"
