name = "ATPLean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["ATPLean"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "ATPLean"

[package]
name = "myproject"
lean_version = "leanprover/lean4:nightly"
require = ["mathlib"]

[dependencies]
mathlib = { git = "https://github.com/leanprover-community/mathlib4", rev = "master" }

[[lean_exe]]
name = "preprocess"
root = "Preprocess"
exeName = "pp"
